import Head from 'next/head';

import Nav from 'components/Nav';
import Header from 'components/Header';
import About from 'components/About';
import Skills from 'components/Skills';
import Work from 'components/Work';
import Showcase from 'components/Showcase';
import Contact from 'components/Contact';
import Footer from 'components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Header />
      <About />
      <Skills />
      <Work />
      <Showcase />
      <Contact />
      <Footer />
    </>
  );
}
